services:
  - type: web
    name: ticketing-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: RENDER
        value: "true"
    disk:
      name: tickets-db
      mountPath: /opt/render/project/src
      sizeGB: 1
